version: "3.7"

services:
  postgres_base:
    image: postgis/postgis:13-3.1-alpine
    container_name: postgres_base_container
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - POSTGRES_HOST=${PG_HOST}
      - POSTGRES_DB=${PG_DB}
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - TZ=Europe/Rome
      - PGTZ=Europe/Rome
    ports:
      - ${PG_PORT}:5432
    volumes:
      - ./docker_volumes/postgresql_data:/var/lib/postgresql/data
      - ./init_docker/init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin4_base:
    container_name: pgadmin4_base_container
    image: dpage/pgadmin4
    restart: always
    networks:
      - proxy
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80" 

networks:
  proxy:
    external: true
