name: Deploy
on:
  pull_request:
    branches: [ main ]
    types: [ closed ]
jobs:
  Build_image_and_publish:    
    runs-on: ubuntu-latest 
    name: Build and Push image
    steps:
      - uses: actions/checkout@v3 
      - name: Build & Push image
        run: |
          docker login -u "francesco.re69@gmail.com" -p "Lillone19" docker.io
          docker build --target development -t 3481974/backend-development-server:backend-development-server \
          --build-arg POSTGRES_HOST=${{secrets.PG_HOST}} \
          --build-arg POSTGRES_DB=${{secrets.PG_DB}} \
          --build-arg POSTGRES_USER=${{secrets.PG_USER}} \
          --build-arg POSTGRES_PASSWORD=${{secrets.PG_PASSWORD}} \
          --build-arg POSTGRES_SCHEMA=${{secrets.PG_SCHEMA}} \
          --build-arg POSTGRES_PORT=${{secrets.PG_PORT}} \
          --build-arg TZ=Europe/Rome \
          --build-arg PGTZ=Europe/Rome .
          docker push docker.io/3481974/backend-development-server:backend-development-server
